---
- name: install dependencies
  apt:
    name: "{{ xtendcash_dependencies }}"
    state: present

- name: download xtendcash source code
  git:
    repo: "{{ xtendcash_source_code }}"
    version: "{{ xtendcash_source_tag }}"
    dest: "{{ xtendcash_install_dir }}/src/{{ xtendcash_source_tag }}"
    separate_git_dir: "{{ xtendcash_install_dir }}/src/.git-{{ xtendcash_source_tag }}"
    update: no
  register: xtendcash_code

- name: make xtendcash
  make:
    chdir: "{{ xtendcash_install_dir }}/src/{{ xtendcash_source_tag }}"
    target: release
  environment:
    CC: "{{ xtendcash_cc | default('gcc') }}"
    CXX: "{{ xtendcash_cxx | default('g++') }}"
    CFLAGS: "{{ xtendcash_cflags | default('-mtune=generic') }}"
    CXXFLAGS: "{{ xtendcash_cxxflags | default('-mtune=generic') }}"
  when: xtendcash_code.changed
