---

- name: make sure source code var is set when building
  assert:
    that:
      - '"{{ xtendcash_source_code }}" != ""'
    fail_msg: "xtendcash_source_code is not set"
    success_msg: "xtendcash source code is set"
  when: xtendcash_build_source

- name: make sure binary download URL is set
  assert:
    that:
      - '"{{ xtendcash_binary_url }}" != ""'
    fail_msg: "xtendcash_binary_url is not set"
    success_msg: "xtendcash binary URL is not set"
  when: not xtendcash_build_source

- name: create xtendcash group
  group:
    name: "{{ xtendcash_group }}"
    state: present

# need shell for prepare_registration
- name: create xtendcash user
  user:
    name: "{{ xtendcash_user }}"
    group: "{{ xtendcash_group }}"
    system: true
    shell: /bin/bash
    state: present

- name: install rsyslog
  apt:
    name: rsyslog
    state: present

- name: make sure rsyslog is enabled and running
  service:
    name: rsyslog
    enabled: yes
    state: started

- name: install fail2ban
  apt:
    name: fail2ban
    state: present

- name: make sure fail2ban is enabled and running
  service:
    name: fail2ban
    enabled: yes
    state: started

- name: install ntp
  apt:
    name: ntp
    state: present

- name: make sure ntp is enabled and running
  service:
    name: ntp
    enabled: yes
    state: started

- name: setup directories
  include_tasks:
    file: setup.yml

- name: install binaries
  include_tasks:
    file: binaries.yml
  when: not xtendcash_build_source

- name: build source code
  include_tasks:
    file: build.yml
  when: xtendcash_build_source

- name: configure system for xtendcashd
  include_tasks:
    file: config.yml

#- name: firewall
